[package]
name = "asve"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed.git" }
raw-window-handle = "0.6"
gstreamer = "0.24.3"
gstreamer-video = "0.24.3"
objc2 = "0.6.3"
objc2-app-kit = "0.3.2"
objc2-foundation = "0.3.2"
